---
- name: Configure Elk VM with Docker
  hosts: elk
  remote_user: azadmin
  become: true
  tasks:

    # Use apt module
    - name: Install docker.io
    apt:
      update_cache: yes
      force_apt_get: yes
      name: docker.io
      state: present
    
    # Use apt module
    - name: Install python3-pip
      apt:
      force_apt_get: yes
      name: python3-pip
      state: present
  
    # Use pip module (It will default to pip3)
    - name: Install Docker module
        pip:
        name: docker
        state: present
    
    # Use command module
    - name: increase virtual mem
    command: sysctl -w vm.max_map_count=262144
    
    # Use sysctl module
    - name: use more mem
      sysctl:
         name: vm.max_map_count
         value: '262144'
         state: present
         reload: yes
    # Use docker_container module
    - name: download and launch a docker ELK container
      docker_container:
         name: elk
         image: sebp/elk:761
         restart_policy: always
         # Please list ports that ELK runs on
         published_ports:
           - 5601:5601
           - 9200:9200