---
  - name: Config webserver vms
    hosts: webservers
    become: true
    tasks
    
    - name: Install docker
      apt:
        name: docker.io
        state: present
        update_cache: yes
        
    - name: Install python3-pip
      apt:
        name: python3-pip
        state: present
     
     - name: Docker via pip
       pip:
         name: docker
         state: present
         
     - name: Install DVWA container
       docker_container:
         name: dvwa
         image: cyberxsecurity/dvwa
         restart_policy: always
         published_ports: 80:80
